// Generated by https://quicktype.io

export interface IBanner {
    _createdAt: string;
    _id:        string;
    _rev:       string;
    _type:      string;
    _updatedAt: string;
    buttonText: string;
    desc:       string;
    discount:   string;
    image:      Image;
    largeText1: string;
    largeText2: string;
    midText:    string;
    product:    string;
    saleTime:   string;
    smallText:  string;
}

export interface Image {
    _type: string;
    asset: Asset;
}

export interface Asset {
    _ref:  string;
    _type: string;
}
